### ISSUE TITLE
How to upload an image?

### ISSUE THREAD

**Issue by SeriousGeorge** [cachapa/firedart#100]
How do you upload an image with flutter/dart? Is there a storage reference?

**Comment by cachapa** [comment]
Firedart does not implement firebase storage.
Currently only auth and database.

**Comment by SeriousGeorge** [comment]
Ah I see. Are thery any plans from your side? I'm searching for a windows desktop solution to upload images to firebase storage. Is there in any chance an additional package that could be combined with yours?

**Comment by cachapa** [comment]
There was an attempt at implementing it in #32 but it was never completed and I'm not sure it even works anymore.

I don't have plans to pick it up since this project is currently on maintenance mode.
I'll be happy to review contributions though.
