### ISSUE TITLE
Please support http version > 0.13.6

### ISSUE THREAD

**Issue by jakusb** [cachapa/firedart#101]
Because no versions of firedart match >0.9.2 <0.10.0 and firedart 0.9.2 depends on http ^0.13.6, firedart ^0.9.2 requires http ^0.13.6.

**Comment by cachapa** [comment]
Blocked on grpc for the same reason.
There's a PR: https://github.com/grpc/grpc-dart/pull/629

**Comment by jakusb** [comment]
> Blocked on grpc for the same reason.
> There's a PR: [grpc/grpc-dart#629](https://github.com/grpc/grpc-dart/pull/629)

As in it is not supported for legacy backwards compatibility reasons?

**Comment by cachapa** [comment]
We can't upgrade the `http` dependency on our end until `grpc` also updates it on theirs because we depend on both packages.
