### ISSUE TITLE
Firestore initialization changed for versions >0.9.0+1

### ISSUE THREAD

**Issue by mzohren** [cachapa/firedart#103]
When following documentation this should be working:

```
    var firebaseAuth = FirebaseAuth(apiKey, prefStore!);
    var fireStore = Firestore(projectId, auth: firebaseAuth);
```

But _the named parameter 'auth' isn't defined._ for Firestore.
Up to 0.9.0+1 this was they way to instantiate a Firestore object.
What is the current way ? I am assuming it is somehow using the new authenticator parameter.
But since it is not documented, I hav no idea how to use it ...

**Comment by cachapa** [comment]
Thanks for the report, we changed how auth works in the latest release and forgot to update the readme
