### ISSUE TITLE
Connection error: Connection is being forcefully terminated.

### ISSUE THREAD

**Issue by LEHOANGLONG0807** [cachapa/firedart#109]
flutter: Handling error gRPC Error (code: 2, codeName: UNKNOWN, message: HTTP/2 error: Connection error: Connection is being forcefully terminated. (errorCode: 10), details: null, rawResponse: null, trailers: {}) using FirestoreGateway._handleError
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: gRPC Error (code: 2, codeName: UNKNOWN, message: HTTP/2 error: Connection error: Connection is being forcefully terminated. (errorCode: 10), details: null, rawResponse: null, trailers: {})

**Comment by cachapa** [comment]
Can you give a bit more context

**Comment by cachapa** [comment]
Closed by #130
