### ISSUE TITLE
verifyIdToken

### ISSUE THREAD

**Issue by SwissCheese5** [cachapa/firedart#26]
Missing from firebase auth. Looked at firebase_admin's implementation and tried copying it over, turns out it's far too complicated. I don't know what classes they have correspond to classes we have.

**Comment by cachapa** [comment]
What's this? A way to just check if the id token is valid?

As far as I know there isn't a request you can make to verify the token. This can actually be done offline by decoding the JWT and verifying the signature.

I have done that for a different project and could import the code here if it makes sense. What do you need it for?

**Comment by SwissCheese5** [comment]
@cachapa https://firebase.google.com/docs/auth/admin/verify-id-tokens

I need this for my backend. I'm porting my java backend to dart native and this is the one missing feature left (well that and firebase storage)

**Comment by cachapa** [comment]
I have a dart-native implementation of that, I'll add it to the project.

**Comment by SwissCheese5** [comment]
Awesome :)

**Comment by sjapps** [comment]
I know this is closed but I have a question. If we're not hitting anything over at firebase to verify, what is keeping someone from generating a token for other users and getting authenticated as that user? Maybe I just don't understand oauth tokens fully.

**Comment by cachapa** [comment]
Every token is cryptographically signed by Google with a rotating key. Verifying the id token involves getting the signing keys directly from Google (via HTTPS) and using them to validate the content of the token.

You can see this in action in https://jwt.io - look at the bottom "verify signature" part.

Offline token validation is an explicit goal of oauth's design to avoid making an extra token verification call for every authenticated request that hits your server.

**Comment by SwissCheese5** [comment]
@cachapa This is the java firebase admin sdk: 
![image](https://user-images.githubusercontent.com/7407478/82727448-5d07ce00-9cf3-11ea-95ac-2ea441c0a201.png)

Your implementation does not check if the token is revoked.

**Comment by cachapa** [comment]
You're welcome to add it if you like :-)

**Comment by SwissCheese5** [comment]
I legitimately don't know anything about this

**Comment by cachapa** [comment]
The documentation isn't very clear here: they say you can check the status of the token but don't specify how to do it and I couldn't find a specific REST call for it.

It might be enough to perform a request against the getUser endpoint just to verify the token though. Do you want to test if this would work?
If so, you might also try performing a HEAD request rather than a POST since we're probably only interested in the return code.

To be honest I think this is a pretty wasteful way of verifying tokens. Firebase tokens are valid for one hour, which means a revoked one would continue working for 60 minutes max.
If you absolutely need to revoke tokens immediately, you might be better off implementing them directly in your service: keep a local list of revoked tokens and compare it against every request. Clear any revoked tokens that are older than 1h to avoid the list growing forever.

Docs: https://firebase.google.com/docs/auth/admin/manage-sessions#detect_id_token_revocation

**Comment by SwissCheese5** [comment]
Storing revoked requests in way more wasteful and is significantly more overhead. Not to mention the issues it would cause as well as not being viable for serverless solutions like mine.

**Comment by cachapa** [comment]
You think storing a set of temporary tokens (which should be almost always empty) is more wasteful than performing an extra HTTP request for every single call?

I see the issue with serverless solutions, but even in that case it might be more efficient to load the set from remote storage than the extra request for every call - assuming your instance lives long enough to handle more than one client request, which in my experience they tend to do.

**Comment by SwissCheese5** [comment]
You mustnt rely on that behavior with serverless. Either way, this is unintended implementation of this behavior. The firebase SDK does this, therefore, firedart must as well.

**Comment by cachapa** [comment]
> You mustnt rely on that behavior with serverless.

It's not relying on it. Loading a list of revoked tokens when launching the instance is probably about as efficient as making a verification request.
I think I'm being misinterpreted here. I'm not against implementing that functionality, I just personally don't think it's that useful and will therefore not invest the implementation effort myself.
If you'd like to try implementing it, I'll gladly merge your PR :-)

> The firebase SDK does this, therefore, firedart must as well.

Not so fast... It's not a design goal of firedart to replicate every single Firebase feature.
I started this project with the intention of scratching my own itch, and over the last few days we've been adding features that scratch yours. That's my vision for this project: implement the features that devs actually need to build their stuff.

**Comment by SwissCheese5** [comment]
I tried to dig into the java SDK source code and found this: https://gist.github.com/SwissCheese5/1ee04c9899a3acfd764f86682f960977
Now most of what I had to dig through is jargon to me, however, from what I understand, if I can port this over, it means we can check if a token is revoked, right? @cachapa 
I'm less asking for you to do this and more asking if what I'm digging into is the correct so I can take the steps necessary to port this over.

**Comment by cachapa** [comment]
I don't see anywhere in that source code where they check if the token is revoked, am I missing something?
All I see is what we already have: verifying the token's contents and signature.

**Comment by sjapps** [comment]
This might be helpful: https://github.com/appsup-dart/firebase_admin/blob/master/lib/src/auth.dart#L198

I've been using that library for verifying the tokens and it does seem to work. I have not tried checking for reinvoked tokens though.

**Comment by SwissCheese5** [comment]
```java
  private boolean isRevoked(FirebaseToken firebaseToken) throws FirebaseAuthException {
    UserRecord user = userManager.getUserById(firebaseToken.getUid());
    long issuedAtInSeconds = (long) firebaseToken.getClaims().get("iat");
    return user.getTokensValidAfterTimestamp() > issuedAtInSeconds * 1000;
  }
```
found it.

**Comment by sjapps** [comment]
Like that library, the check for checking for reinvoked tokens should be optional imo. 

It doesn't seem to hard to implement

```
  /// Verifies the decoded Firebase issued JWT is not revoked. Returns a future
  /// that resolves with the decoded claims on success. Rejects the future with
  /// revocation error if revoked.
  Future<IdToken> _verifyDecodedJwtNotRevoked(IdToken decodedIdToken) async {
    // Get tokens valid after time for the corresponding user.
    var user = await getUser(decodedIdToken.claims.subject);
    // If no tokens valid after time available, token is not revoked.
    if (user.tokensValidAfterTime != null) {
      // Get the ID token authentication time.
      final authTimeUtc = decodedIdToken.claims.authTime;
      // Get user tokens valid after time.
      final validSinceUtc = user.tokensValidAfterTime;
      // Check if authentication time is older than valid since time.
      if (authTimeUtc.isBefore(validSinceUtc)) {
        throw FirebaseAuthError.idTokenRevoked();
      }
    }
    // All checks above passed. Return the decoded token.
    return decodedIdToken;
  }
```

**Comment by SwissCheese5** [comment]
Wait... Isn't firedart doing this already, but non-optionally?

https://github.com/cachapa/firedart/blob/9d91872bb4daa19b2383fcb0b739ac2d112b773b/lib/auth/token/jwt.dart#L30-L35

**Comment by sjapps** [comment]
I think the idea here is to check against the authTime. If there is a new token for the user, it will have a new authTime and render reinvoked tokens invalid.

**Comment by SwissCheese5** [comment]
Also worth noting that there are extra parameters in the jwt class that are not exposed in the verifyIdToken in firedart.

**Comment by SwissCheese5** [comment]
So we need to get the user object. I'm not sure @cachapa's implementation handles this.

I see we have the userId `  String get userId => _payload.subject;` but nothing else.

**Comment by SwissCheese5** [comment]
Okay, so diving into the firebase_admin code, here's the steps I'm going to do

- Post request to `https://identitytoolkit.googleapis.com/$version/projects/$projectId`
- Decode the json map
- Convert the map to a User object because we might as well
- Use the auth time from that to compare.

**Comment by SwissCheese5** [comment]
PR #30

**Comment by cachapa** [comment]
Ok, so they did exactly what we were planning to do: try to get the user and if that fails we know the token is invalid. Seems pretty straightforward.

**Comment by cachapa** [comment]
@sjapps issuing a new token for the user does not implicitly revoke old tokens. A single user can have multiple active, valid tokens e.g. if he's using multiple devices.
