### ISSUE TITLE
You shouldn't need to await .doc()

### ISSUE THREAD

**Issue by SwissCheese5** [cachapa/firedart#28]
Firestore makes it so you can get a document reference without marking it as a write. It's just a reference to the document without any data, so no sub collection and no fields/maps.

The way to get the data is to do doc(...).get(). This is marked as a read by firestore.

The way we have it in firedart is doc(...) directly gets the data, and if you want to set data you have to do (await doc(..)).set(...). This is supposedly marked as a read and a write. Very unnecessary and unexpected behavior.

**Comment by SwissCheese5** [comment]
(I was looking at another similar library by accident)

**Comment by sjapps** [comment]
So firedart doesn't cause a read and write on set, correct?

**Comment by SwissCheese5** [comment]
Yes ignore this please.
