### ISSUE TITLE
firebase_auth_test.dart is failing

### ISSUE THREAD

**Issue by SwissCheese5** [cachapa/firedart#31]
I was checking if I was attempting a sign in correctly and it seems that firebase_auth_test is failing on all tests...

![image](https://user-images.githubusercontent.com/7407478/82805330-8314a600-9e8c-11ea-8063-fd0676d1a059.png)

I did not modify the auth_gateway or user_gateway, the _post method itself is failing for some reason. The data is correct as I compared it to the documentation and breakpointed the body map, it is using my email and password, and firebase auth is using my firebase web key.

@cachapa Can you please run firebase_auth_test and tell me if it passes? If it does, then the problem is on my side.

**Comment by cachapa** [comment]
All the tests are passing on my side

**Comment by SwissCheese5** [comment]
Hm... Very odd. Thank you

**Comment by SwissCheese5** [comment]
![image](https://user-images.githubusercontent.com/7407478/82870922-67b3a480-9f39-11ea-9bca-28dba51ebc90.png)
This is with postman, trying out the google api directly, any idea what's going on?

**Comment by SwissCheese5** [comment]
Ah, so the problem was that I didn't have sign in with email/pass enabled in firebase auth in my project. Simple mistake.
