### ISSUE TITLE
400: Bad Request running signIn()

### ISSUE THREAD

**Issue by SwissCheese5** [cachapa/firedart#37]
I was making tests to test my verifyIdToken implementation in Dartbase Admin SDK. Naturally, I needed to acquire a user id token first and the only way to do that is from a client. So I used firedart as a dev-dependency for testing only and ran the following code:

```dart
  setUpAll(() async {
    await Firebase.initialize(projectId, await ServiceAccount.fromFile(serviceAccountPath));

    fd.FirebaseAuth.initialize(webApiKey, fd.VolatileStore());

    await FirebaseAuth.initialize();
  });

  test('Verify Token', () async {
    await fd.FirebaseAuth.instance.signIn(email, pass);
    var token = await fd.FirebaseAuth.instance.tokenProvider.idToken;

    var id = await FirebaseAuth.instance.verifyIdToken(token);
    expect(id != null, true);
    print(id);
  });
```
crash at: `    await fd.FirebaseAuth.instance.signIn(email, pass);`
with the following message:
```
package:firedart/auth/auth_gateway.dart 48:7  AuthGateway._post

Exception: 400: Bad Request
```
Which is right here:
https://github.com/cachapa/firedart/blob/master/lib/auth/auth_gateway.dart#L37-L52

**Comment by SwissCheese5** [comment]
Ugh, seems firebase overrided my authentication with a google sign in after doing it once despite being registered with email/pass. My bad.

**Comment by cachapa** [comment]
I would recommend avoiding using the singleton version i.e. `.instance` if you're mixing multiple auth objects.

I think that might solve your issue.
