### ISSUE TITLE
How to listen to document changes in one collection?

### ISSUE THREAD

**Issue by anandsubbu007** [cachapa/firedart#46]
When i listen to one collection. it read all document in that collection instead of showing only changes which led to too much read.

**Comment by cachapa** [comment]
It should only trigger on documents which change. If you're seeing more reads this probably means that the documents are changing without you being aware.

You can also try filtering by using `where()`.

**Comment by anandsubbu007** [comment]
if i use where(). it only showing get().
i can't able to watch collection with where condition,
please help me with this.

```
class StreamFB extends StatefulWidget {
  StreamFB({Key key}) : super(key: key);

  @override
  _StreamFBState createState() => _StreamFBState();
}

class _StreamFBState extends State<StreamFB> {
  Stream<List<Document>> stream;
  @override
  void initState() {
    // QueryReference ref =
    stream = Firestore.instance.collection('test').stream;
    // .where('LastUpdate', isLessThan: date)
    // .get()
    // .asStream();
    super.initState();
  }

  void handledata(List<Document> documents) {
    print('-->');
    documents.forEach((e) {
      print('ID > ${e.id} | ${e.path}');
      print('MAP > ${e.map}');
      print('MAP > ${e.createTime} | ${e.updateTime}');
    });
  }

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<List<Document>>(
      stream: stream,
      initialData: [],
      builder: (BuildContext context, AsyncSnapshot snapshot) {
        handledata(snapshot.data ?? []);
        return Scaffold();
      },
    );
  }
}
```

I'm using the above method to listen to changes. 
if i change one document it result in all document in that one collection

**Comment by cachapa** [comment]
You're right, I don't think you can filter streams. It's a limitation of Firebase BTW.

**Comment by anandsubbu007** [comment]
Ok thanks for your response.

**Comment by anandsubbu007** [comment]
May I know any way to listen to collection with query like in cloud Firestore.
I'm trying to implement this function in flutter desktop (windows). But I searched a lot till I can't able to find any solution. I also searched for rest api to implement this function. But I can't able to find any thing.

Please help me to implement this function in flutter desktop.

Thanks for your plugin & reply

**Comment by cachapa** [comment]
It's currently not possible with Firedart

**Comment by markbreuss** [comment]
> It's currently not possible with Firedart

Would it be possible to implement this Feature a s PR.
