### ISSUE TITLE
Calling Document.stream causes unnecessary network activity

### ISSUE THREAD

**Issue by esDotDev** [cachapa/firedart#52]
I've been doing some performance testing, and it seems the lack of local caching is a pretty major issue.

Without it, my app incurs many read calls each time a widget is rebuilt, for example, a StreamBuilder watching a 100 item collection, if the parent of that widget plays a 1s animation, you could incur 6000 read calls right there (60fps, 100 reads each frame). The same interaction with the native sdk shows 0 read calls.

I'm just curious if this is known behavior, or is there a better way to sync your UI to the stream.

Also any chance of local cache being added if this is the cause?
Cheers,

**Comment by cachapa** [comment]
Firedart explicitly has no caching since that adds a whole new layer of complexity to the projects that I'd rather no approach before other aspects that in my mind have higher priority.

I'm not sure I understand your example fully though. A StreamBuilder shouldn't be triggering read calls, unless there's a bug somewhere (either in mine, or in your code).

**Comment by esDotDev** [comment]
Oh, that would be great if it were a bug and not actually a cache thing, I was just guessing. 

So I have something like this:
```
 StreamBuilder<List<Document>>(
              stream: Firestore.instance.collection("/users/shawn@test.com/books").stream,
              builder: (_, AsyncSnapshot<List<Document>> snapshot) {
                if (!snapshot.hasData) return StyledSpinner();
                return RandoColoredBox(
                    child: Row(children: snapshot.data.map((e) => SelectableText(" --> ${e.id}.    ")).toList()));
              }),
```
In init(), I have:
```
Timer.periodic(Duration(milliseconds: 100), (timer) => setState(() {}))
```
I have 3 records in this table, but the read calls shoot throught the roof:
![image](https://user-images.githubusercontent.com/736973/101318373-7569b100-381d-11eb-8664-ca35187478f7.png)

**Comment by esDotDev** [comment]
It seems to spawn a new snapshot listener everytime `.stream` is called:
![image](https://user-images.githubusercontent.com/736973/101319566-6f74cf80-381f-11eb-9d1a-44a6a9c26452.png)

This is all from that one example, running for ~3minutes.

**Comment by cachapa** [comment]
I just checked the code and it seems the stream setup happens every time you call .stream, which is causing those reads.
So I guess the issue in on my side :-)

Anyway, my recommendation for now would be for you to find a way to cache the stream object to avoid calling .stream on every rebuild.
Thanks for the report!
