### ISSUE TITLE
How to cancel document .listen stream correctly

### ISSUE THREAD

**Issue by guyluz11** [cachapa/firedart#55]
I am trying to get pass #43 for now.
So I am restarting the stream each hour using    
```
 Timer.periodic(const Duration(minutes: 1), (Timer t)  {
      print('Restarting stream');
      listenToDataBaseHelper();
    });
```

I have static var in the class  `static StreamSubscription<Document> listenToDataBaseStream;` that I use to save the stream and cancel it before creating the new one like this:

```
await listenToDataBaseStream?.cancel();
listenToDataBaseStream = _cloudValueChangeEntity.listenToDataBase().listen((document) {
```
But I found out that `.cancel` on the stream does not remove the `Snapshot listeners` and I get ever increasing spikes in `Snapshot listeners`  and `Reads` as there are a lot of listeners that are not canceled.

![image](https://user-images.githubusercontent.com/9304740/102885015-5bee7900-445b-11eb-8a4d-7249a688b1cc.png)

How should I cancel `.listen` stream correctly.

**Comment by guyluz11** [comment]
@cenomla can you instruct me how to cancel document .listen stream correctly now that you have merged the pull request?

**Comment by cenomla** [comment]
@guyluz11 the listen request stream is automatically cleaned up once there are no more listeners. Using `StreamSubscription.cancel` should do the trick now. One thing I should mention is that the listen request stream is cleaned up in a future so it doesn't happen immediately and if the same stream is listened to again before the clean up happens the clean up is canceled.

**Comment by guyluz11** [comment]
Tested it now and it looks like it worked.
Thanks @cenomla
