### ISSUE TITLE
UserCollection class not found

### ISSUE THREAD

**Issue by VenceslauCassinda** [cachapa/firedart#56]
Peek Problem message from Editor: Undefined name 'UserCollection'.
Try correcting the name to one is defined...........

My pubspec.yaml
![tempsnip](https://user-images.githubusercontent.com/58729800/103437429-f9019c80-4c27-11eb-8b56-3e3f11e0799b.png)

My main.dart where I set the project id
![tempsnip2](https://user-images.githubusercontent.com/58729800/103437455-382fed80-4c28-11eb-860f-f68273f2a345.png)

Where I really used Firedart Package and getting the error by calling UserCollection class.
Pleass help me.
![tempsnip3](https://user-images.githubusercontent.com/58729800/103437467-68778c00-4c28-11eb-8ec1-c19fd600d7c1.png)

**Comment by cachapa** [comment]
UserCollection isn't a part of Firedart, so it seems like it should be part of your project, or maybe some other package.

In any case you might have more success asking on Stackoverflow.
