### ISSUE TITLE
Migrate code to NNBD

### ISSUE THREAD

**Issue by esDotDev** [cachapa/firedart#60]
I know this may be a long shot, but is there any way you can think of to get this to nnbd?

**Comment by CaramelDunes** [comment]
My shot at it: https://github.com/CaramelDunes/firedart

I wish FirebaseExtended had plans for a Dart version. I'm closely monitoring FirebaseExtended/flutterfire#3243.
Otherwise, we could start a community effort. I was thinking we could follow the official API and provide Dart implementations for the `platform_interface` packages.

**Comment by cachapa** [comment]
I pushed a quick update to 0.9.0+1
All tests are passing so I assume it should be working fine, but please report if you find any hard edges.

**Comment by esDotDev** [comment]
Thx a lot!

**Comment by Ehesp** [comment]
> My shot at it: [CaramelDunes/firedart](https://github.com/CaramelDunes/firedart)
> 
> I wish FirebaseExtended had plans for a Dart version. I'm closely monitoring [FirebaseExtended/flutterfire#3243](https://github.com/FirebaseExtended/flutterfire/issues/3243).
> Otherwise, we could start a community effort. I was thinking we could follow the official API and provide Dart implementations for the `platform_interface` packages.

@CaramelDunes it might be worth looking at https://github.com/FirebaseExtended/flutterfire/discussions/3359#discussioncomment-57117 - there's a good few reasons (aside from a huge amount of work) why this isn't as simple as it might seem.

**Comment by esDotDev** [comment]
I don't know how "good" these reasons are. I mean they make sense from the paclage author's POV, but they ring hollow for a developer who bought into the firebase story and is now kinda screwed.

The fact everything can not be ported is not a valid reason to not port what can be. Auth and Firestore are the most commonly used and both of these can be implemented as pure REST API. If offline support is not available for desktop platforms, no one is going to mind ( because it's desktop).

The fact it is a lot of work is unfortunate for the plugin team, but this is some fallout of previous decisions they made to save work that is now coming back to bite. Had they wrote it in pure dart in the first place, which would have been more up-front work, then they wouldn't be in this situation now.

If the team was really taking seriously cross-platform firebase support, the use of Native SDK's that were never going to work on Windows or Linux should have been a non-starter.  

I understand these decisions were made yrs ago, but things have changed now. I'm not even sure what the plan is now, seems like the team is just throwing up their hands and shrugging? "Well we can't port it all, and it's hard, so... sorry?".

**Comment by CaramelDunes** [comment]
> 
> 
> > My shot at it: [CaramelDunes/firedart](https://github.com/CaramelDunes/firedart)
> > I wish FirebaseExtended had plans for a Dart version. I'm closely monitoring [FirebaseExtended/flutterfire#3243](https://github.com/FirebaseExtended/flutterfire/issues/3243).
> > Otherwise, we could start a community effort. I was thinking we could follow the official API and provide Dart implementations for the `platform_interface` packages.
> 
> @CaramelDunes it might be worth looking at [FirebaseExtended/flutterfire#3359 (comment)](https://github.com/FirebaseExtended/flutterfire/discussions/3359#discussioncomment-57117) - there's a good few reasons (aside from a huge amount of work) why this isn't as simple as it might seem.

Thanks for linking this insightful comment.
I agree with @esDotDev  that we should port what can be. Firestore and Auth would be enough for most projects, and I think it is important if Flutter wants its single codebase philosophy to be taken seriously on Desktop.
