### ISSUE TITLE
signInWithCustomToken is not implemented

### ISSUE THREAD

**Issue by ertong** [cachapa/firedart#76]
Currently, it is possible to signIn by email/password or anonymously.
But in "native" FirebaseAuth it is possible to FirebaseAuth.instance.signInWithCustomToken and use server-generated token.

As far as I understand, it is possible to add to auth_gateway.dart something like

```
Future<User> signInWithCustomToken(String token) async =>
      _auth('signInWithCustomToken', {'token': token, 'returnSecureToken':"true"});

```
as described in https://cloud.google.com/identity-platform/docs/use-rest-api#section-verify-custom-token

This call does not return localId, but it is expected in auth_gateway.dart. Not sure whether it is required here at all.

**Comment by cachapa** [comment]
Implemented in 0.9.4
