### ISSUE TITLE
What is equivalent to FieldValue.ServerTimeStamp() ?

### ISSUE THREAD

**Issue by YogeshLegendkiller** [cachapa/firedart#80]
Hi Thanks for fantastic library is there any equivalent to FieldValue.ServerTimeStamp()?

**Comment by fenchai23** [comment]
did you find a solution for this?

I am looking for an implementation for `TimeStamp.now()`

**Comment by Nico04** [comment]
Same here, a equivalent of FieldValue.ServerTimeStamp() would be very nice :)

**Comment by cachapa** [comment]
Contributions are welcome!

Be the change you want to see in the world 🙂

**Comment by cachapa** [comment]
It seems Firebase Timestamps are translated to regular DateTime types.

I'm closing this issue unless someone can argue otherwise.
