### ISSUE TITLE
Outdated Readme?

### ISSUE THREAD

**Issue by luistrivelatto** [cachapa/firedart#84]
First of all, thanks a lot for doing this! I just wanted to have some offline pure-Dart scripts to do stuff with Firestore, and I was struggling with several other packages until finding this. It's great!

I noticed that the Readme says, under "Limitations" of Firestore:

> Collection queries (limit, sort, etc.) are currently not supported.

However, going through the API I see methods like `CollectionReference.orderBy`, `CollectionReference.limit`, and others. Are these another thing, or is the Readme outdated?

**Comment by RomjanHossain** [comment]
this package is OUTDATED. it was last updated a year ago

**Comment by bksubhuti** [comment]
I am very happy that you are maintaining this package.  There is no other 5 OS firestore option.
We will probably be adding soon to our app with roughly 3500 users on all 5 OS combine, but 2600 android.
I also noticed that some of the needed functions are not listed..
I tested the first 2 and they worked well.


Future<void> resetPassword(String email) => _authGateway.resetPassword(email);

  Future<void> requestEmailVerification({String? langCode}) =>
      _userGateway.requestEmailVerification(langCode: langCode);

  Future<void> changePassword(String password) =>
      _userGateway.changePassword(password);

**Comment by cachapa** [comment]
Thanks for the comments.

Which functions aren't listed, and where?

**Comment by bksubhuti** [comment]
I pasted them in my original message.  I didn't see that anywhere.


```
Future resetPassword(String email) 
Future requestEmailVerification({String? langCode})
Future changePassword(String password)
```

Furthermore requestEmailVerification will allow for the opportunity for the user to qualify his email, but controlling what is done by that user is done manually.

Here is some code from a practice file I made.
I can upload most of a sample project with notifiers, if you wish.  It is my pleasure to help especially this week when I have more time.  Most of it was chatgpt.   It was able to navigate based on other knowledges of firebase and I also took a peek at the files as well.



```
  Future<void> addBookmark(String bookID, String note, int page) async {
    try {
      var auth = FirebaseAuth.instance;
      User user = await auth.getUser();
      debugPrint('User: $user');

      if (user.emailVerified == false) {
        debugPrint('Email not verified!');
        throw Exception('Email not verified!');
      }

      var userBookmarksCollection = Firestore.instance
          .collection('users')
          .document(Prefs.email)
          .collection('bookmarks');

      await userBookmarksCollection.add({
        'bookID': bookID,
        'note': note,
        'page': page,
      });
    } catch (e) {
      debugPrint('Error adding bookmark: $e');
      throw e; // Optionally rethrow to handle the error on the UI side.
    }
  }

```

**Comment by bksubhuti** [comment]
well.. I guess it is my duty to help.. I think that a better and more elaborate example would help out a lot.
I'm not so smart with flutter and now with gpt.. i'm not getting any better.  However, I have a gpt plus account and a long running thread with my prototype and sample program.  
I can tell it to improve the example program.  I will also try to improve the readme file.
Do the example programs need to be a single file?  It seems that way in most pub.dev specs.


Perhaps this needs a separate issue or is this it ?  
https://github.com/cachapa/firedart/issues/24 
I was wondering if there are any plans for offline cache?  This is half the point of using firestore.  although it seems that firebase also has cache as well.

I have integrated user sign in and fetching data into my main app but it is still in the testing and prototype stage.
With sign in at the beginning of the app, it seems to be quite fast when a simple sync button is called.  Great work!

**Comment by cachapa** [comment]
> I can tell it to improve the example program. I will also try to improve the readme file.

Please do not use AI tools to generate contributions. I don't have a lot of time to dedicate to maintaining this project so changes should be minimal and easy to review.
I also don't trust AI tools to produce robust code on their own.
If you don't feel you're experienced enough with Dart to contribute yet, then it's ok to postpone your contributions to a later time.

>Do the example programs need to be a single file? It seems that way in most pub.dev specs.

Ideally yes, so potential users can have a quick reference to the core package functionality.
You can have multiple examples if you want to demonstrate different use cases to avoid making a very complex example, but that's not very common.

> Perhaps this needs a separate issue or is this it ?

#24 is about adding Firebase Storage, which is a separate service in the Firebase ecosystem to store files, e.g. images. I actually have working code for that but integrating it into Firedart requires a large effort that I'm not able to invest right now.

> I was wondering if there are any plans for offline cache? 

I considered it back then, but didn't have a good way to fit it in the existing implementation, as it would mean Firedart would have to take on the responsibility of storing data. It's also hard to do conflict resolution with Firebase, which is required for proper offline data caching.

**Comment by bksubhuti** [comment]
I should be able to give basic additional commands in a example file "by hand and in a single file.  I will test it.  The original working sample yes was done by gpt plus.  There is a huge difference between 3.5 and plus account .  But I can make a small example now that I understand.  
It should have add delete and also this create.  I don't have my computer with me right now , but also so of the functions I mentioned above..


For cache..
We write to SQLite db.
I will be at first writing to a db and the manually syncing via sync button. . The original idea was to swap the db with firestore when they choose this mode, but it won't be such a problem.

We appreciate your help and making this library independently.  It is really the job of flutter and firebase but this is the way it is.  We also use a html core library for multiplatform use.

Our app is a non-commercial Buddhist Text reading app and I'm a monk.

I have a strategy for this my sync by adding fileds
Action
Actiondate
Synchronize (bool)
Deletes will actually be a soft delete.and still exist.

I wonder if there is a better way to have an umbrella sync table. That keeps track of table name primary key and those fields stated above .  But for now, I'll integrate into the Bookmarks table directly.  The usage is to sync bookmarks and notes  into other other devices .  We will probably  have other tables synced  later as well.

Maybe that strategy helps you too.

**Comment by cachapa** [comment]
Again, please do not use AI tools to contribute to this repository. I'm really pressed for time and do not want to spend it manually reviewing generated code.
I have a responsibility to keep this project's high quality so I'd rather have missing stuff than quick fixes.

If you want to sync a SQL database, then I recommend using [crdt_sync](https://github.com/cachapa/crdt_sync) instead of Firebase.
It already integrates with Sqlite and PostgresSQL and uses CRDTs for conflict management, which is a much more robust way to synchronize data than the simple timestamps Firebase uses.

What it lacks in relation to Firebase is authentication, but you could still use Firedart for that part.

**Comment by bksubhuti** [comment]
okay.. I'm glad you are making a high quality library.  I guess I picked the right library to work with.
as for the other one, crdt_sync, it does look interesting.  I forwarded it to another developer who does more advanced stuff for us.  The main reason firestore is appealing is we don't need to host the server.  For now, I think a manual sync will do the work needed.  When we start adding other features it will be interesting to explore an automatic system  Perhaps the cache will be done later one for that.  Surely you are the one who is capable to implement.  I feel confident in your abilities by your rejection of my help :).
Again your work is much appreciated.  Sorry I was not skilled enough to help.

**Comment by cachapa** [comment]
I meant to say that the other (big) drawback of crdt_sync is you need to self-host it.
I might implement a hosting service at some point, but for now it has that very high requirement.

In any case, thank you for understanding and I look forward to your contributions when you feel more confident in your skills. Best of luck with your project!

**Comment by cachapa** [comment]
I created #120 to track the missing documentation, and will close this one because the discussion went completely off track :-)
