### ISSUE TITLE
Stream terminated by peer

### ISSUE THREAD

**Issue by maxpill** [cachapa/firedart#87]
On calling .set() method an unhandled gRPC `Stream was terminated by peer`  error is thrown.

```
        Firestore.instance
            .collection(path)
            .document(docPath)
            .set(value);
```

```
Handling error gRPC Error (code: 2, codeName: UNKNOWN, message: HTTP/2 error: Stream error: Stream was terminated by peer (errorCode: 7)., details: null, rawResponse: null, trailers: {}) using FirestoreGateway._handleError
Unhandled exception:
gRPC Error (code: 2, codeName: UNKNOWN, message: HTTP/2 error: Stream error: Stream was terminated by peer (errorCode: 7)., details: null, rawResponse: null, trailers: {})
```

<img width="800" alt="Debugger" src="https://user-images.githubusercontent.com/43760021/164491387-98df8856-225f-4370-9511-6a6ad67dee7a.png">

**Comment by maxpill** [comment]
@cachapa

**Comment by dovahkinnn** [comment]
I'm getting this error too, did you find a solution?

**Comment by maxpill** [comment]
Unfortunately not. Used another library

**Comment by marcglasberg** [comment]
Hey @maxpill, could you please tell us which library are you using? Thanks!

**Comment by maxpill** [comment]
Hello @marcglasberg !

Ive tried various approaches and it came out to be a problem with library.

I do not remember what the case was exactly and cannot check right now, but I checked it for you and the version of the library we have used is

firedart: ^0.9.0+1, 

Max

**Comment by cachapa** [comment]
Closing this since the problem seems to be fixed per the last comment.

**Comment by patricknicolosi** [comment]
Still the same problem!!! You can't close an issue like this

**Comment by cachapa** [comment]
@patricknicolosi please be more respectful, everybody here is a volunteering their time.

Can you still reproduce the problem?
