### ISSUE TITLE
Could you please support "signInWithCustomToken" in FirebaseAuth?

### ISSUE THREAD

**Issue by eximius313** [cachapa/firedart#98]
Currently `FirebaseAuth` supports only `signIn(email, password)` and `signInAnonymously()`

Could you please support `signInWithCustomToken` according to the [Reference docs](https://firebase.google.com/docs/auth/admin/create-custom-tokens?hl=en#sign_in_using_custom_tokens_on_clients)?

Thank you in advance.

**Comment by cachapa** [comment]
Sorry but this library is currently on maintenance mode.

I would be happy to accept contributions though.

**Comment by eximius313** [comment]
Sure! Thanks.

**Comment by cachapa** [comment]
Check PR #97 perhaps it fits your use case, or at least for inspiration.

**Comment by eximius313** [comment]
@cachapa, could you please take a look at my PR (https://github.com/cachapa/firedart/pull/104)?

**Comment by cachapa** [comment]
Hi @eximius313 thanks for your contribution!
The code looks good, I just had a couple of suggestions and questions which I think will be quick to address.
